exports.HTTP_STATUS = {
  SUCCESS: 200,
  CREATE_SUCCESS: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  DUPLICATED: 409,
  SERVER_ERROR: 500,
};

exports.DELIVERY_STATUS = {
  PENDING: 'pending',
  DELIVERING: 'delivering',
  ARRIVED: 'arrived',
};
