name: Build & Deploy

on:
  push:
    branches: [ develop ]

defaults:
  run:
    shell: bash

env:
  ACTION_NAME: action_deploy

jobs:
  build:
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: |
        yarn --cwd ./client install
        yarn --cwd ./server install
    
    # 임시방편으로, CI 환경변수 비활성화
    - name: Build client
      run: CI=false yarn --cwd ./client build
    
    - name: Create .env
      run: |
        cd server
        echo ${{ secrets.ENV }} > .env
        
    - name: Archive sources
      run: tar -cpvzf ./$GITHUB_SHA.tgz *
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
 
    - name: Upload to S3
      run: |
        aws s3 cp \
          --region ap-northeast-2 \
          ./$GITHUB_SHA.tgz s3://bmart-6/$ACTION_NAME/$GITHUB_SHA.tgz

    - name: Code Deploy
      run: |
        aws deploy create-deployment \
        --application-name bmart-6-codedeploy \
        --file-exists-behavior OVERWRITE \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --deployment-group-name ec2-instance-web \
        --s3-location bucket=bmart-6,key=$ACTION_NAME/$GITHUB_SHA.tgz,bundleType=tgz
